## Урок 2

### Практическое задание, часть 1

In [1]:
import numpy as np

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
   
   Произведения матриц $AB$ и $BA$ не возможно т.к. не выполняется условие - кол-во столбцов первой матрицы равно кол-ву строк второй матрицы
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
   
   Произведения матриц $AB$ возможно и размерности полученной матрицы - $2\times 3$. Произведения матриц $BA$ не возможно.
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
   
   Произведения матриц $AB$ возможно и размерности полученной матрицы - $8\times 8$. Произведения матриц $BA$ возможно и размерности полученной матрицы - $3\times 3$.
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
   
   Произведения матриц $AB$ и $BA$ возможно и размерность полученных матриц - $4\times 4$.

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}.$$


In [4]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

print(f'Матрица С = A + B\n{a + b}')

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]


$$A\cdot B=\begin{pmatrix}
1\cdot4+(-2)\cdot0 & 1\cdot(-1)+(-2)\cdot5\\ 
3\cdot4+0\cdot0 & 3\cdot(-1)+0\cdot5
\end{pmatrix}=\begin{pmatrix}
4 & -11\\ 
12& -3 
\end{pmatrix}.$$
/
$$B\cdot A=\begin{pmatrix}
4\cdot1+(-1)\cdot3 & 4\cdot(-2)+(-1)\cdot0\\ 
0\cdot1+5\cdot3 & 0\cdot(-2)+5\cdot0
\end{pmatrix}=\begin{pmatrix}
1 & -8\\ 
15& 0 
\end{pmatrix}.$$

In [6]:
print(f'Матрица AB\n{np.dot(a, b)}')

Матрица AB
[[  4 -11]
 [ 12  -3]]


In [15]:
print(f'Матрица AB\n{np.dot(b, a)}')

Матрица AB
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$$D=3A-2B+4C=
\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}-
\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}+
\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}=
\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$$

In [19]:
a1 = np.array([[1, 7], [3, -6]])
b1 = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

print(f'Матрица D = 3A - 2B + 4C\n{(3 * a1 - 2 * b1) + 4 * c}')

Матрица D = 3A - 2B + 4C
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3 
\end{pmatrix}.$$

In [8]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Транспонированная матрица:\n{A.T}')

Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]


$AA^{T}=\begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot(-2) & 4\cdot2+1\cdot3\\ 
5\cdot4+(-2)\cdot1 & 5\cdot5+(-2)\cdot(-2) & 5\cdot2+(-2)\cdot3\\ 
2\cdot4+3\cdot1 & 2\cdot5+3\cdot(-2) & 2\cdot2+3\cdot3
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}.$

In [13]:
print(f'Матрица AAT\n{np.dot(A, A.T)}')

Матрица AAT
[[17 18 11]
 [18 29  4]
 [11  4 13]]


$A^{T}A=\begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot(-2)+2\cdot3\\ 
1\cdot4+(-2)\cdot5+3\cdot2 & 1\cdot1+(-2)\cdot(-2)+3\cdot3
\end{pmatrix}=\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}.$

In [14]:
print(f'Матрица ATA\n{np.dot(A.T, A)}')

Матрица ATA
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [ ]:
def summa():  
    #Вводим размер матриц
    r1 = int(input('Элементов в строке в матрицы1: '))
    c1 = int(input('Элементов в солбце в матрицы1: ')) 
    r2 = int(input('Элементов в строке в матрицы2: '))
    c2 = int(input('Элементов в солбце в матрицы2: '))
    
    print('Вводим элементы матрицы A')
    #Вводим элементы матрицы A
    A = []
    for i in range(r1) :
        A.append([])
        for j in range(c1) :
            A[i].append(int(input()))        
    print('A = ')
    for q in A :
        print(q)
    print('Вводим элементы матрицы B')
    #Вводим элементы матрицы B
    B = []
    for q in range(r2) :
        B.append([])
        for w in range(c2) :
            B[q].append(int(input()))
    print('B = ')
    for q in B :
        print(q)
 
#Умножение
    s=0     #сумма
    t=[]    #временная матрица
    C=[] # конечная матрица
    if len(B)!=len(A[0]):
        print "Матрицы не могут быть перемножены"        
    else:
        r1=len(A) #количество строк в первой матрице
        c1=len(A[0]) #Количество столбцов в 1   
        r2=c1           #и строк во 2ой матрице
        c2=len(B[0])  # количество столбцов во 2ой матрице
        for z in range(0,r1):
            for j in range(0,c2):
                for i in range(0,c1):
                   s=s+A[z][i]*B[i][j]
                t.append(s)
                s=0
            C.append(t)
            t=[]           
    return C

### Практическое задание, часть 2

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}=sin^2x+cos^2x=1$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}=4\cdot5\cdot9=180$$

In [25]:
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

print(f'Определитель:\n{np.linalg.det(b):.0f}')

Определитель:
180


   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=
1\cdot\begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix}-
2\cdot\begin{vmatrix}
4 & 6\\ 
7 & 9
\end{vmatrix}+
3\cdot\begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix}=1\cdot(5\cdot9-8\cdot6)-2\cdot(4\cdot9-7\cdot6)+3\cdot(4\cdot8-7\cdot5)= \\
=-3+12-9=0.
$$

In [23]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{c}')
print(f'Определитель:\n{np.linalg.det(c):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})=16$;
    
   б) $det(A^{T})=4$;
    
   в) $det(2A)=2^n\cdot4$, где n - кол-во строк (столбцов) матрицы.

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю.<br>
Строки 1 и 2 линейно зависимы => определитель матрицы равен 0 => матрица является вырожденной.

In [26]:
f = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

print(f'Определитель:\n{np.linalg.det(f):.0f}')

Определитель:
0


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [1]:
x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

NameError: name 'np' is not defined

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [28]:
x1 = [0, 0, 2, 1]
y1 = [0, 0, 2, 2]
z1 = [0, 0, 4, 3]
q1 = [2, 3, 5, 6]

a = np.array([x1, y1, z1, q1])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
